### ISSUE TITLE
Widgets shouldn't show on pages

### ISSUE THREAD

**Issue by ckenst** [themebeans/stash#2]
Widgets are showing on individual Pages in addition to Blog posts but shouldn't:

- This is on the latest version of WP (5.2.1) and the latest version of Stash (2.0.5)
- Example page: http://67.205.136.211/about/publications/

Let me know if you need more information to reproduce.

**Comment by richtabor** [comment]
Resolved by #3

**Comment by ckenst** [comment]
@richtabor I updated my site to use 2.0.6 and the issue is still there. Thoughts?

**Comment by ckenst** [comment]
@richtabor I over-wrote / replaced `stash/template-parts/content-page.php` within my child-theme by removing the code for a widget inclusion. This works for me but I'm not sure if this is how it was originally done or not....? So now it works on my site..lol
